export enum ActionTypes {
  COMMON_SETLOGIN = "COMMON_SETLOGIN",
  COMMON_SETEMAIL = "COMMON_SETEMAIL",
  COMMON_SETPASSWORD = "COMMON_SETPASSWORD",
  COMMON_CONFIRMPASSWORD = "CONFIRMPASSWORD",
  COMMON_SET_ISAUTH = "COMMON_SET_ISAUTH",
  COMMON_SET_USERID = "COMMON_SET_USERID",
  COMMON_SET_ERRORMESSAGE = "COMMON_SET_ERRORMESSAGE",
  COMMON_SET_ISRESET = "COMMON_SET_ISRESET",
  COMMON_SET_ACTIVENAVBAR = "COMMON_SET_ACTIVENAVBAR",
}
