export enum AuthUserActionTypes {
  COMMON_SETLOGIN = "COMMON_SETLOGIN",
  COMMON_SETEMAIL = "COMMON_SETEMAIL",
  COMMON_SETPASSWORD = "COMMON_SETPASSWORD",
  COMMON_CONFIRMPASSWORD = "CONFIRMPASSWORD",
}

export enum ChatActionTypes {
  SET_CURRENTCHAT = "SET_CURRENTCHAT",
  SET_CHATMEMBERS = "SET_CHATMEMBERS",
}

export enum LoaderActionTypes {
  LOAD_CHATS = "LOAD_CHATS",
  LOAD_MESSAGES = "LOAD_MESSAGES",
  LOAD_SEARCH = "LOAD_SEARCH",
  LOAD_BLOCKED = "LOAD_BLOCKED",
}

export enum RootActionTypes {
  COMMON_SET_ISAUTH = "COMMON_SET_ISAUTH",
  COMMON_SET_USERID = "COMMON_SET_USERID",
  COMMON_SET_ERRORMESSAGE = "COMMON_SET_ERRORMESSAGE",
  COMMON_SET_ISRESET = "COMMON_SET_ISRESET",
  COMMON_SET_ACTIVENAVBAR = "COMMON_SET_ACTIVENAVBAR",
  SET_USERINFO = "SET_USERINFO",
}

export enum SidebarActionTypes {
  SIDEBAR_SETDIALOGS = "SIDEBAR_SETDIALOGS",
  SIDEBAR_SETBLOCKEDUSERS = "SIDEBAR_SETBLOCKEDUSERS",
  SIDEBAR_SETFOUNDUSERS = "SIDEBAR_SETFOUNDUSERS",
  SET_GROUPCHATIMAGE = "SET_GROUPCHATIMAGE",
  SET_GROUPCHATNAME = "SET_GROUPCHATNAME",
  SET_GROUPCHATMEMBERS = "SET_GROUPCHATMEMBERS",
}
