export enum ActionTypes {
  COMMON_SETLOGIN = "COMMON_SETLOGIN",
  COMMON_SETEMAIL = "COMMON_SETEMAIL",
  COMMON_SETPASSWORD = "COMMON_SETPASSWORD",
  COMMON_CONFIRMPASSWORD = "CONFIRMPASSWORD",
  COMMON_SET_ISAUTH = "COMMON_SET_ISAUTH",
  COMMON_SET_USERID = "COMMON_SET_USERID",

  SIGN_UP = "SIGN_UP",
  SIGN_IN = "SIGN_IN",
  SEND_RESET_LINK = "SEND_RESET_LINK",
  RESET_PASSWORD = "RESET_PASSWORD"
}
